Docs/digital accessibility
nics-tw/resilience-material pull request #18
Opened 2024-12-23 06:23 UTC by Luxame

2024-12-23 07:12 UTC, nonumpa requested changes
我先給一點建議

2024-12-23 07:12 UTC, nonumpa commented on digital-accessibility.md
> +      - [6. 我們依靠某種工具來判斷網站的無障礙程度。](#6-我們依靠某種工具來判斷網站的無障礙程度)
感覺這些細項不用放進目錄，查看原始檔案目錄沒有把這些細項放進去，因為這裡沒有大標題小標題之分，重復使用數字條列方式看起來怪怪的

2024-12-23 07:12 UTC, nonumpa commented on digital-accessibility.md
> +        - [相關連結：](#相關連結)
這些細項也是

2024-12-23 07:12 UTC, nonumpa commented on digital-accessibility.md
> +6. 表明機關「穩定管制」程度的狀態(參見[[可及性狀態]](#可及性狀態))。
```suggestion
6. 表明機關「穩定管制」程度的狀態(參見[可及性狀態](#可及性狀態))。
```

2024-12-23 07:12 UTC, nonumpa commented on digital-accessibility.md
> +> 您可以在本文「你的角色如何做出貢獻」章節中的法務及政風人員，找到更多關於法制化的資訊。
```suggestion
> 您可以在本文[「你的角色如何做出貢獻」](#你的角色如何做出貢獻)章節中的[法務及政風人員](#法務及政風人員)，找到更多關於法制化的資訊。
```

2024-12-23 07:12 UTC, nonumpa commented on digital-accessibility.md
> +#### 你的角色如何做出貢獻？
原檔案使用三號標題(`###`)，不確定為什麼沒有跟上面同級標題一起編號 (如果一起編號的話，這個項目應該是 10)

2024-12-23 07:12 UTC, nonumpa commented on digital-accessibility.md
> +#### 齊心協力，保障數位可及性！
原檔案使用三號標題(`###`)，不確定為什麼沒有跟上面同級標題一起編號 (如果一起編號的話，這個項目應該是 11)

2024-12-23 07:12 UTC, nonumpa commented on digital-accessibility.md
> +    - [3. 法制化](#3-法制化)
```suggestion
    - [1 引言](#1-引言)
    - [2 網頁可及性與身心功能障礙](#2-網頁可及性與身心功能障礙)
    - [3 法制化](#3-法制化)
```

2024-12-23 07:12 UTC, nonumpa commented on digital-accessibility.md
> +    - [3. 法制化](#3-法制化)
原檔案這些數字後面沒有 `.`，先暫時調得跟它一致

2024-12-23 07:12 UTC, nonumpa commented on digital-accessibility.md
> +### 1. 引言
```suggestion
### 1 引言
```

2024-12-23 07:12 UTC, nonumpa commented on digital-accessibility.md
> +### 2. 網頁可及性與身心功能障礙
```suggestion
### 2 網頁可及性與身心功能障礙
```

2024-12-23 07:12 UTC, nonumpa commented on digital-accessibility.md
> +### 3. 法制化
```suggestion
### 3 法制化
```

2024-12-23 07:12 UTC, nonumpa commented on digital-accessibility.md
> +  - [目錄](#目錄)
這兩項應該不用放進目錄

2024-12-23 07:28 UTC, nonumpa commented on digital-accessibility.md
> +model〕觀點理解「障礙」一詞。當上下文指涉特定法律時，準用台灣法律用語，譯為「身心障礙」。當上下文不局限於法定身心障礙時，譯為「身心功能障礙」，可能包含未經法定程序證明〔符合法定身心障礙鑑定基準但未取得法定身分資格〕、尚未法制化〔未納入法定身心障礙鑑定向度或基準的情形〕或不同身心功能狀態者〔任何人在不同生命階段中可能經歷的狀態〕。「身心功能障礙」並非採用「醫療模式」，翻譯方法希望有助於讓讀者
發現`〔〕` 這種括號只在這邊使用到，查看原檔案也是這樣使用，可能要確認一下是誤植還是有特殊意涵。

2024-12-24 07:50 UTC, Luxame commented
@nonumpa 這邊有根據建議做相對的調整異動，較有疑義有跟 @IK-Ngoo 討論確認了。
感謝~

2024-12-24 08:05 UTC, nonumpa commented
@Luxame 還有 `齊心協力，保障數位可及性！` 標題大小跟目錄沒改到（太多評論被隱藏了），這個改完應該就可以先 merge 了！

2024-12-24 09:30 UTC, nonumpa approved these changes

2024-12-24 09:50 UTC, merged